### ISSUE TITLE
npm start 出错

### ISSUE THREAD

**Issue by yhhwpp** [yukrain/koa-antd-admin#4]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart koa-admin-admin@0.0.1
6 info start koa-admin-admin@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info koa-admin-admin@0.0.1 Failed to exec start script
9 verbose stack Error: koa-admin-admin@0.0.1 start: `NODE_ENV=development node-dev --harmony app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid koa-admin-admin@0.0.1
11 verbose cwd F:\workplace\koa-antd-admin
12 error Windows_NT 6.1.7601
13 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error koa-admin-admin@0.0.1 start: `NODE_ENV=development node-dev --harmony app.js`
17 error Exit status 1
18 error Failed at the koa-admin-admin@0.0.1 start script 'NODE_ENV=development node-dev --harmony app.js'.
18 error This is most likely a problem with the koa-admin-admin package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=development node-dev --harmony app.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs koa-admin-admin
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls koa-admin-admin
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by yhhwpp** [comment]
已解决
